version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install SSH Client
          command: sudo apt-get update && sudo apt-get install -y openssh-client
      - run:
          name: Add SSH Host Key
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan ec2-34-229-134-142.compute-1.amazonaws.com >> ~/.ssh/known_hosts
      - run:
          name: Decode and Write SSH Key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_KEY" | base64 --decode > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "Contents of id_rsa:"
            cat ~/.ssh/id_rsa
      - run:
          name: Transfer Files to Windows Server
          command: |
            scp -o StrictHostKeyChecking=no -r ./ CircleCI@ec2-34-229-134-142.compute-1.amazonaws.com:C:\ComputingProject
      - run:
          name: Execute Deployment Script
          command: ssh -o StrictHostKeyChecking=no CircleCI@ec2-34-229-134-142.compute-1.amazonaws.com 'powershell -File C:\ComputingProject\deploy.ps1'

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
