version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Run Tests
          command: echo "Run your tests here"
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:S8lObqbvNteO8HNn2pqWnfNxeYm7s+hmahqe4ZyEyoc"
      - run:
          name: Execute Deployment Script
          command: ssh -v -T $SSH_USER@$SSH_HOST "cd C:\ComputingProject\ComputingProject-main && git pull origin main"
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: main # only deploy on the main branch
