version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:S8lObqbvNteO8HNn2pqWnfNxeYm7s+hmahqe4ZyEyoc"
      - run:
          name: Execute Deployment Script
          command: ssh $SSH_USER@$SSH_HOST "powershell -File C:/ComputingProject/deploy.ps1"
